// <auto-generated />
namespace CarPooler.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class FirstAlpha : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstAlpha));
        
        string IMigrationMetadata.Id
        {
            get { return "201506100459317_FirstAlpha"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
